### ISSUE TITLE
Error Running `gem install`

### ISSUE THREAD

**Issue by evanleck** [rubinius/docker#2]
Hi Rubinius! Sorry if this doesn't belong here, I'm trying to figure out what's going on and haven't had any luck anywhere else (Google) so I figured I'd ask here.

I am trying to run a little Puma app inside of the `rubinius/docker:ubuntu-14.04` image but am getting the error:

``` sh
Step 7 : RUN gem install bundler
 ---> Running in e1052452bcd1
gem: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
The command '/bin/sh -c gem install bundler' returned a non-zero code: 127
```

My Dockerfile looks like this:

``` dockerfile
# Our base rubinius image.
FROM rubinius/docker:ubuntu-14.04

# The directory we will run from.
ENV APP_HOME /var/app/current

# Create our app directory.
RUN mkdir -p $APP_HOME

# Add the gemfile and bundle it
WORKDIR /tmp
COPY Gemfile /tmp/
COPY Gemfile.lock /tmp/
RUN gem install bundler
RUN bundle install --without development test

# Add our code there
WORKDIR $APP_HOME
COPY . $APP_HOME

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Run Puma
CMD 'puma config.ru'
```

And it seems to choke at `RUN gem install bundler`. Here's the whole dump after running `docker build -t puma-rbx .`

``` sh
Sending build context to Docker daemon 604.7 kB
Step 1 : FROM rubinius/docker:ubuntu-14.04
 ---> 225a36eae180
Step 2 : ENV APP_HOME /var/app/current
 ---> Running in a131b3c44d8d
 ---> f5f04c68d1fb
Removing intermediate container a131b3c44d8d
Step 3 : RUN mkdir -p $APP_HOME
 ---> Running in 6bc6c7794b2d
 ---> ad409fa38d28
Removing intermediate container 6bc6c7794b2d
Step 4 : WORKDIR /tmp
 ---> Running in 24cbff5a20cc
 ---> 6e317c44b449
Removing intermediate container 24cbff5a20cc
Step 5 : COPY Gemfile /tmp/
 ---> f85dc90648e8
Removing intermediate container 985782a28de8
Step 6 : COPY Gemfile.lock /tmp/
 ---> 785268cf133a
Removing intermediate container 369afe49443a
Step 7 : RUN gem install bundler
 ---> Running in e1052452bcd1
gem: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
The command '/bin/sh -c gem install bundler' returned a non-zero code: 127
```

Again, my apologies if this issue doesn't belong here! Thank you!

**Comment by brixen** [comment]
@evanleck no apologies necessary! It looks like we need to install libedit in the image. LLVM has a dependency on libedit, but the Ubuntu packages for LLVM don't specify it! Very annoying. I'll edit the Docker image file and it will probably take about 30 min for the build to finish.

**Comment by evanleck** [comment]
Awesome! Thanks so much, I was totally confused!

**Comment by brixen** [comment]
@evanleck looks like [this build succeeded](https://hub.docker.com/r/rubinius/docker/builds/bq6njpuypn9u86hwwhlfmma/). Would you be able to retry your build?

**Comment by evanleck** [comment]
Yup! I retried and am still getting the same error. Just so I know I'm doing it right, I deleted the image listed when I ran `docker images` and re-ran the `docker build` command. Is there anything else I should do before? I got the following after running `build`

``` sh
Sending build context to Docker daemon 604.7 kB
Step 1 : FROM rubinius/docker:ubuntu-14.04
ubuntu-14.04: Pulling from rubinius/docker
6599cadaf950: Pull complete
23eda618d451: Pull complete
f0be3084efe9: Pull complete
52de432f084b: Pull complete
a3ed95caeb02: Pull complete
bcb2bd70e0fb: Pull complete
b92410f84f00: Pull complete
39af7225eb7a: Pull complete
5d3dc8c65cf7: Pull complete
ded51ca8919d: Pull complete
Digest: sha256:2f3a423d34e26880180ee06da41c3fd3d83f198f3105978289b2c9262a0511c6
Status: Downloaded newer image for rubinius/docker:ubuntu-14.04
 ---> 225a36eae180
Step 2 : ENV APP_HOME /var/app/current
 ---> Running in 620b46c5ea4c
 ---> e858bb453037
Removing intermediate container 620b46c5ea4c
Step 3 : RUN mkdir -p $APP_HOME
 ---> Running in 4e15da6f14c1
 ---> 562bb60e8d77
Removing intermediate container 4e15da6f14c1
Step 4 : WORKDIR /tmp
 ---> Running in 4031f4907170
 ---> 68f852243aba
Removing intermediate container 4031f4907170
Step 5 : COPY Gemfile /tmp/
 ---> e398d351af82
Removing intermediate container 0fee0503b80e
Step 6 : COPY Gemfile.lock /tmp/
 ---> ec08ecda4a5a
Removing intermediate container c5a5ec265914
Step 7 : RUN gem install bundler
 ---> Running in c637e5848ea6
gem: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
The command '/bin/sh -c gem install bundler' returned a non-zero code: 127
```

**Comment by brixen** [comment]
@evanleck hm, not a Docker expert but that seems correct. Is your repo public so I could try building here?

**Comment by brixen** [comment]
@evanleck ahh, I think you may need to run `docker pull rubinius/docker`.

```
$ docker pull rubinius/docker
Using default tag: latest
latest: Pulling from rubinius/docker
8c84b6166fa5: Pull complete
e827f893c695: Pull complete
88026c51afa0: Pull complete
0313304981b1: Pull complete
d941f7cd1f1f: Pull complete
365e3b9f6032: Pull complete
bd0860bf82e6: Pull complete
d861e420821b: Pull complete
0038c690e06f: Pull complete
8207bc04906e: Pull complete
Digest: sha256:7a2ae6ce97bfc44e70ed7be794ea173202c25cb883ae30b251cf62bc2a6896c6
Status: Downloaded newer image for rubinius/docker:latest
MacBook:docker brianshirai$ docker run -it rubinius/docker:latest bash
root@ca647771cb26:/# ruby -v
rubinius 3.30 (2.2.2 282c0312 2016-05-06 3.6.0) [x86_64-linux-gnu]
root@ca647771cb26:/# gem -v
2.6.2
root@ca647771cb26:/# gem install bundler
Fetching: bundler-1.12.3.gem (100%)
Successfully installed bundler-1.12.3
Parsing documentation for bundler-1.12.3
Installing ri documentation for bundler-1.12.3
Done installing documentation for bundler after 44 seconds
1 gem installed
root@ca647771cb26:/# find /usr/lib -name libedit\*
/usr/lib/x86_64-linux-gnu/libedit.so
/usr/lib/x86_64-linux-gnu/libedit.a
/usr/lib/x86_64-linux-gnu/pkgconfig/libedit.pc
/usr/lib/x86_64-linux-gnu/libedit.so.2
/usr/lib/x86_64-linux-gnu/libedit.so.2.0.47
```

**Comment by evanleck** [comment]
Ahhhh perhaps!

To answer your previous question, it's a work in progress for my company so it's not public. However, I made a quick demo repo that I have the same problem with at https://github.com/evanleck/rbx-docker-failing-libedit

Clone and run `docker build -t rbx-test .` and it fails for me.

**Comment by evanleck** [comment]
Also, I'm not using the "latest" tag but the "ubuntu-14.04" tag. Does that matter? Is there one for Ubuntu 16.04 yet?

**Comment by brixen** [comment]
@evanleck ah, that probably explains it. We dropped 12.04 (due to unavailability of newer LLVM packages) and so I switched 14.04 to latest. We don't yet build 16.04 because it's not available on Travis CI (where we build the binaries that the Docker images use), but I hope to set up Concourse soon (http://concourse.ci) so we can build 16.04.

Could you try with `rubinius/docker:latest`?

**Comment by evanleck** [comment]
Ahhh makes sense! Yup, `rubinius/docker:latest` gets past `gem install bundler` now I just have to figure out what I need for some of my other gems. Thank you so much!

**Comment by brixen** [comment]
@evanleck good to hear! So, I'm not totally clear on the conventions for tagging builds, so I've added `ubuntu-14.04` back as a tag, which is the same as latest. I'm not sure if people would be confused if we didn't have a latest, so I'll leave it for now as an alias of ubuntu-14.04. Feedback welcomed.

**Comment by evanleck** [comment]
I'm pretty new to all of this docker stuff too so I'm not 100% what to do. I think keeping the `latest` tag is definitely the right way to go.

**Comment by brixen** [comment]
@evanleck ok, cool, we'll keep it. Thanks for the feedback.

**Comment by eLod** [comment]
@brixen i'm still experiencing the same error, however i am trying to use the docker image in a CI job.

the output of the job:

```
Using Docker executor with image rubinius/docker:latest ...
Pulling docker image rubinius/docker:latest ...
...
$ gem install bundler -v 1.12.3
gem: error while loading shared libraries: libedit.so.2: cannot open shared object file: No such file or directory
```

it happens both with latest and ubuntu-14.04

edit: an `apt-get install libedit2` fixes the problem

**Comment by brixen** [comment]
@eLod sorry about that, I pushed a one-off update here but failed to make the change in the script that automatically updates the Dockerfile, so the change go overwritten. I've re-pushed the change here and I'll update the script.
